### PR TITLE
feat(gateways): add smpp gateway configuration

### PR DESCRIPTION
**Pull request by Mohammer5**
Fixes DHIS2-10387

Adds a new type of gateway configuration (smpp), includes tests.

### CODE REVIEW

**Review by mediremi — APPROVED** [review]

**Comment by Mohammer5** [comment]
@mediremi You removed the `visitWhenStubbed` helper from `cypress/support/index.js`.  What was the reasoning for this? There are a lot of tests that use that helper and it's not provided by `@dhis2/cypress-commands`, maybe I missed sth?

**Comment by mediremi** [comment]
@Mohammer5 It looks like I forgot to restore `visitWhenStubbed` after updating `@dhis2/cypress-commands` and `cypress/support/index.js` :sweat:

We should enable E2E tests in `.github/workflows/dhis2-verify-app.yml` so that this doesn't happen again

**Comment by Mohammer5** [comment]
> We should enable E2E tests in .github/workflows/dhis2-verify-app.yml so that this doesn't happen again. Are you happy to do that in this PR or should I create a separate one with that change?

I think this would need the network shim feature that @HendrikThePendric released. I can try to add that, it'd be nice to have

**Comment by Mohammer5** [comment]
@mediremi I made some very minor changes since you reviewed. Could you take a look and approve again?

**Review by mediremi — APPROVED** [review]

**Comment by Mohammer5** [comment]
CC @HendrikThePendric 
https://jira.dhis2.org/browse/TECH-533
https://jira.dhis2.org/browse/TECH-534

**Pull request merged**
